version: '3.6'
services:
  aligner:
    build: .
    image: aligner:latest
    restart: unless-stopped
    ports:
        - "${APP_PORT}:80"
    volumes:
      - ${APP_DATA_PATH}:/app/data
      - ${APP_IMG_PATH}:/app/static/img